name: HumineStaff
main: humine.com.main.StaffMain
author: SDAChess
version: 2.1.2
api-version: 1.14
commands:
  invsee:
  endsee:
  annonce:
  vanish:
  voteban:
  automessage:
  lien:
  permission:
  tpsmonitor:
  upvote:
